language: rust
install:
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
script:
  - rustc main.rs
  - ./main &
  - echo test > testfile
  - python -m SimpleHTTPServer &
  - curl --socks5 localhost:8089 http://127.0.0.1:8000/testfile > socks5
  - curl --socks4 localhost:8089 http://127.0.0.1:8000/testfile > socks4
  - curl --socks4a localhost:8089 http://127.0.0.1:8000/testfile > socks4a
  - diff testfile socks5
  - diff testfile socks4
  - diff testfile socks4a

